[tool.poetry]
name = "renovate-rollback-pr"
version = "0.1.0"
description = ""

[tool.poetry.dependencies]
python = "^3.10"
celery = "5.2.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
